# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/microcai/gentoo-zh.git

[yureek-overlay]
location = /var/db/repos/yureek-overlay
sync-type = git
sync-uri = https://github.com/yureekus/yureek-overlay.git

[ayugram]
location = /var/db/repos/ayugram
sync-type = git
sync-uri = https://github.com/OverLessArtem/ayugram-ebuild-gentoo.git

[kde]
location = /var/db/repos/kde
sync-type = git
sync-uri = https://anongit.gentoo.org/git/proj/kde.git

[xarblu-overlay]
location = /var/db/repos/xarblu-overlay
sync-type = git
sync-uri = https://github.com/xarblu/xarblu-overlay.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git
